<center>
    <h5>Click on the letters to form each of the words given below.</h5>
</center>
<div class="row">
    <div class="col-md-7">
        <table class="scramble-table" id="puzzle4-table">
            <tr>
                <td>E</td>
                <td>A</td>
                <td>A</td>
                <td>C</td>
                <td>E</td>
                <td>J</td>
                <td>A</td>
                <td>D</td>
                <td>E</td>
                <td>A</td>
                <td>P</td>
                <td>I</td>
            </tr>
            <tr>
                <td>T</td>
                <td>N</td>
                <td>A</td>
                <td>I</td>
                <td>M</td>
                <td>A</td>
                <td>A</td>
                <td>Z</td>
                <td>E</td>
                <td>M</td>
                <td>P</td>
                <td>P</td>
            </tr>
            <tr>
                <td>I</td>
                <td>T</td>
                <td>N</td>
                <td>T</td>
                <td>E</td>
                <td>D</td>
                <td>H</td>
                <td>L</td>
                <td>L</td>
                <td>E</td>
                <td>E</td>
                <td>E</td>
            </tr>
            <tr>
                <td>Z</td>
                <td>A</td>
                <td>G</td>
                <td>R</td>
                <td>T</td>
                <td>N</td>
                <td>T</td>
                <td>L</td>
                <td>Q</td>
                <td>T</td>
                <td>R</td>
                <td>A</td>
            </tr>
            <tr>
                <td>N</td>
                <td>N</td>
                <td>A</td>
                <td>I</td>
                <td>I</td>
                <td>O</td>
                <td>K</td>
                <td>A</td>
                <td>T</td>
                <td>H</td>
                <td>I</td>
                <td>R</td>
            </tr>
            <tr>
                <td>U</td>
                <td>Z</td>
                <td>R</td>
                <td>N</td>
                <td>R</td>
                <td>M</td>
                <td>P</td>
                <td>N</td>
                <td>I</td>
                <td>Y</td>
                <td>D</td>
                <td>L</td>
            </tr>
            <tr>
                <td>K</td>
                <td>A</td>
                <td>N</td>
                <td>E</td>
                <td>U</td>
                <td>A</td>
                <td>O</td>
                <td>A</td>
                <td>E</td>
                <td>S</td>
                <td>O</td>
                <td>S</td>
            </tr>
            <tr>
                <td>R</td>
                <td>N</td>
                <td>E</td>
                <td>E</td>
                <td>Z</td>
                <td>I</td>
                <td>A</td>
                <td>Y</td>
                <td>Z</td>
                <td>T</td>
                <td>T</td>
                <td>A</td>
            </tr>
            <tr>
                <td>E</td>
                <td>I</td>
                <td>T</td>
                <td>M</td>
                <td>A</td>
                <td>D</td>
                <td>B</td>
                <td>O</td>
                <td>P</td>
                <td>A</td>
                <td>L</td>
                <td>P</td>
            </tr>
            <tr>
                <td>O</td>
                <td>T</td>
                <td>E</td>
                <td>E</td>
                <td>T</td>
                <td>U</td>
                <td>S</td>
                <td>X</td>
                <td>Y</td>
                <td>N</td>
                <td>O</td>
                <td>P</td>
            </tr>
            <tr>
                <td>Y</td>
                <td>E</td>
                <td>L</td>
                <td>R</td>
                <td>R</td>
                <td>J</td>
                <td>A</td>
                <td>S</td>
                <td>P</td>
                <td>E</td>
                <td>R</td>
                <td>H</td>
            </tr>
            <tr>
                <td>A</td>
                <td>Q</td>
                <td>U</td>
                <td>A</td>
                <td>M</td>
                <td>A</td>
                <td>R</td>
                <td>I</td>
                <td>N</td>
                <td>E</td>
                <td>L</td>
                <td>I</td>
            </tr>
            <tr>
                <td>E</td>
                <td>N</td>
                <td>I</td>
                <td>L</td>
                <td>A</td>
                <td>M</td>
                <td>R</td>
                <td>U</td>
                <td>O</td>
                <td>T</td>
                <td>I</td>
                <td>R</td>
            </tr>
            <tr>
                <td>S</td>
                <td>A</td>
                <td>I</td>
                <td>D</td>
                <td>I</td>
                <td>U</td>
                <td>S</td>
                <td>A</td>
                <td>E</td>
                <td>L</td>
                <td>A</td>
                <td>E</td>
            </tr>
        </table>
    </div>
    <div class="col-md-2">
        <div id="puzzle4-words" class="word-list"></div>
    </div>
    <div class="col-md-3">
        <h5>Remaining Time: <span id="timer-puzzle4">2:00</span></h5>
    </div>
</div>

<button class="btn btn-primary" id="complete-puzzle4" style="float:right;margin-top:10px;width:250px">
    Submit
</button>